#!/usr/bin/env python3

"""
 ____            _   _____         _   
|  _ \ _   _ ___| |_|_   _|____  _| |_ 
| |_) | | | / __| '_ \| |/ _ \ \/ / __|
|  __/| |_| \__ \ | | | |  __/>  <| |_ 
|_|    \__,_|___/_| |_|_|\___/_/\_\\__|
                                       
v.1.2

Project Homepage: 	https://robotmachine.github.io/PushText
Project Source:		https://github.com/robotmachine/PushText

PushText
Command line tool for [Pushover](http://pushover.net)
(C)2013 Brian A. Carter (robotmachine@gmail.com)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import os, sys, urllib, http.client, configparser, textwrap, argparse

global ptVer
ptVer = str("1.2")
settings = os.path.expanduser("~/.ptrc")
config = configparser.ConfigParser()
conn = http.client.HTTPSConnection("api.pushover.net:443")

def main():
	parser = argparse.ArgumentParser(description='PushText: Command line tool for http://pushover.net', prog='pt')
	parser.add_argument('-u','--user',
		action='store', dest='user', default=None,
		help='User key instead of reading from settings. Requires --token.')
	parser.add_argument('-t','--token',
		action='store', dest='token', default=None,
		help='Token key instead of reading from settings. Requires --user.')
	parser.add_argument('-m','--message',
		action='store', dest='WORDS', default="PushText",
		help='Message to send. Default is "PushText"')
	parser.add_argument('-d','--device',
		action='store', dest='DEV', default=None,
		help='Device name to receive message. Default sends to all devices.')
	parser.add_argument('--title',
		action='store', dest='TITLE', default='PushText',
		help='Title or application name. Default is PushText')
	parser.add_argument('--url',
		action='store', dest='URL', default=None,
		help='Optional URL to accompany your message.')
	parser.add_argument('--urltitle',
		action='store', dest='UTITLE', default='PushText URL',
		help='Title to go with your URL.')
	parser.add_argument('-p', '--priority',
		action='store', dest='PRIORITY', default=None,
		help='Priority level. "High" ignores quiet hours and "Low" sends as quiet. Default is normal.')
	args = parser.parse_args()
	read_config(token=args.token, user=args.user, WORDS=args.WORDS, DEV=args.DEV, TITLE=args.TITLE, URL=args.URL, UTITLE=args.UTITLE, PRIORITY=args.PRIORITY)

def read_config(token, user, WORDS, DEV, TITLE, URL, UTITLE, PRIORITY):
	if token is None and user is None:
		if os.path.exists(settings):
			config.read(settings)
			token = config['PushText']['token']
			user = config['PushText']['user']
			message(token, user, WORDS, DEV, TITLE, URL, UTITLE, PRIORITY)
		if not os.path.exists(settings):
			set_config()
	elif token is not None and user is not None:
		message(token, user, WORDS, DEV, TITLE, URL, UTITLE, PRIORITY)

def message(token, user, WORDS, DEV, TITLE, URL, UTITLE, PRIORITY):
	if PRIORITY is None:
		PRI2=0
	elif PRIORITY is not None:
		if (PRIORITY in ["High","high","Hi","HI","hi","H","h"]):
			PRI2=1
		elif (PRIORITY in ["Low","low","Lo","LO","lo","L","l"]):
			PRI2=-1
		else:
			PRI2=0

	if DEV is None and URL is None:
		conn.request("POST", "/1/messages.json",
			urllib.parse.urlencode({
				"token": token,
				"user": user,
				"title": TITLE,
				"message": WORDS,
				"priority": PRI2,
			}), { "Content-type": "application/x-www-form-urlencoded" })

	elif DEV is not None and URL is None:
		conn.request("POST", "/1/messages.json",
			urllib.parse.urlencode({
				"token": token,
				"user": user,
				"title": TITLE,
				"message": WORDS,
				"device": DEV,
				"priority": PRI2,
			}), { "Content-type": "application/x-www-form-urlencoded" })

	elif DEV is None and URL is not None:
		conn.request("POST", "/1/messages.json",
			urllib.parse.urlencode({
				"token": token,
				"user": user,
				"title": TITLE,
				"url": URL,
				"url_title": UTITLE,
				"message": WORDS,
				"priority": PRI2,
			}), { "Content-type": "application/x-www-form-urlencoded" })

	elif DEV is not None and URL is not None:
		conn.request("POST", "/1/messages.json",
			urllib.parse.urlencode({
				"token": token,
				"user": user,
				"title": TITLE,
				"url": URL,
				"url_title": UTITLE,
				"message": WORDS,
				"device": DEV,
				"priority": PRI2,
			}), { "Content-type": "application/x-www-form-urlencoded" })

	else:
		print("Oops, you bwoke it.")
		quit()

	response=conn.getresponse()
	if response.status is 200:
		quit()
	else:
		print("Oops. You bwoke it.")
		print("Pushover sez:", response.status, response.reason)

def set_config():
	print(textwrap.dedent("""
	Leave the API key blank to use
	my app. I cannot see the messages
	that you send. Otherwise, you will 
	need to create your own app 
	with Pushover and provide the token.
	https://pushover.net/apps
	"""))
	token = input("API Token: ")
	if (token == ""):
		token = "VRC3JcAazvpi3KkilC8HFS6Kp0pI7X"
	print(textwrap.dedent("""
	Your user key is found on your 
	Pushover.net Dashboard	
	https://pushover.net
	"""))
	user = input("User Key: ")
	config ['PushText'] = {'token': token,
			       'user': user}		
	with open(settings, 'w') as configfile:
		config.write(configfile)
	print("Settings saved!")
	quit()

def PrintVersion():
	print("PushText v."+ptVer+"\n\n(C)2013 Brian A. Carter\nrobotmachine@gmail.com\nhttps://robotmachine.github.io/PushText")
main()
